FROM node:22-alpine
RUN apk add --no-cache g++ make py3-pip libc6-compat

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ../../ .
ENV NODE_ENV=development
EXPOSE 3000
CMD ["npm", "run", "dev"]