FROM node:22-alpine
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /app
# Install dependencies
COPY package*.json ./
RUN npm ci
# Setup user
RUN addgroup -g 1001 -S servicegroup
RUN adduser -S serviceagent -u 1001
USER serviceagent
# Run build
COPY ../../ .
RUN npm run build
COPY --chown=serviceagent:servicegroup /app/.next ./.next
COPY --chown=serviceagent:servicegroup /app/node_modules ./node_modules
COPY --chown=serviceagent:servicegroup /app/package.json ./package.json
COPY --chown=serviceagent:servicegroup /app/public ./public

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]