FROM node:22-alpine
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /app
# Install dependencies
#COPY package*.json ./
COPY ../../ ./
RUN npm ci
# Setup user
RUN addgroup -g 1001 -S servicegroup
RUN adduser -S serviceagent -u 1001
USER serviceagent
# Run build
RUN npm run build
ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]