# This workflow will build a docker container, publish it to Google Container
# Registry

name: 'Build and Publish to registry'

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'nestosoft-web'
  REGION: 'europe-west2' 
  GAR_LOCATION: 'europe-west2-docker.pkg.dev/nestosoft-devops/nestosoft-web'

jobs:
   
  build-push-artifact:
    # https://vishalbulbule.medium.com/create-github-actions-self-hosted-runner-on-google-cloud-6ae15d62c742
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        
      - name: "Use gcloud CLI"
        run: "gcloud info"
        
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
      - id: get-tag
        name: Get tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build Dev Image
        run: docker build . --file ./docker/Dockerfile_dev -t nestosoft-web-dev
      
      - name: Tag Dev Image
        run: |- 
          docker tag nestosoft-web-dev ${{ env.GAR_LOCATION }}/nestosoft-web-dev:latest
          docker tag nestosoft-web-dev ${{ env.GAR_LOCATION }}/nestosoft-web-dev:${{ steps.get-tag.outputs.short_ref }}

      - name: Publish Dev image
        run: docker push ${{ env.GAR_LOCATION }}/nestosoft-web-dev

      - name: Check images
        run: gcloud artifacts docker images list ${{ env.GAR_LOCATION }}/nestosoft-web-dev --include-tags

