# This workflow will build a docker container, publish it to Google Container
# Registry

name: 'Build and Publish to registry'

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'nestosoft-web'
  REGION: 'europe-west2' 
  GAR_LOCATION: 'europe-west2-docker.pkg.dev/nestosoft-devops/nestosoft-web'

jobs:
   
  build-push-artifact:
    # https://vishalbulbule.medium.com/create-github-actions-self-hosted-runner-on-google-cloud-6ae15d62c742
    runs-on: self-hosted
    
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        
      - name: "Use gcloud CLI"
        run: "gcloud info"
        
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
      - name: Build image
        run: docker build . --file infrastructure/docker/Dockerfile --target production --tag ${{ env.GAR_LOCATION }}
        working-directory: ~/_work/nestosoft_web/nestosoft_web
      
      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
