name: Deploy to Digital Ocean

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Deploy the app
        run: |
          doctl apps create-deployment ${{secrets.DO_APP_ID}} --format ID,Cause,Progress,Phase,Created,Updated -t ${{ secrets.DO_TOKEN }} --wait true
